package migrate

// v2FixtureJSON is a config in v2's own shape, seeded from v2's defaults and
// then given the kind of non-default values a real profile carries. It exists so
// the conversion is exercised against real key names and value types rather than
// ones invented to suit it.
const v2FixtureJSON = `{
 "ageRatingBadgePosition": "inherit",
 "ageRatingBadgeStyle": null,
 "ageRatingTileColor": "",
 "aggregateAccentBarVisible": true,
 "backdropArtworkSource": "tmdb",
 "backdropBottomRatingsRow": false,
 "backdropEpisodeArtwork": "series",
 "backdropImageSize": "normal",
 "backdropImageText": "clean",
 "backdropQualityBadgePreferences": [],
 "backdropQualityBadgesMax": null,
 "backdropRatingPreferences": [
  "tmdb",
  "letterboxd"
 ],
 "backdropRatingsMax": 2,
 "backdropRemuxDisplayMode": "composite",
 "backdropStreamBadges": "auto",
 "fanartKey": "",
 "genreBadgeTileAccentColor": "",
 "lang": "fr",
 "logoArtworkSource": "tmdb",
 "logoBackground": "transparent",
 "logoBottomRatingsRow": false,
 "logoQualityBadgePreferences": [],
 "logoQualityBadgesMax": null,
 "logoRatingPreferences": [],
 "logoRatingStyle": "plain",
 "logoRatingsMax": null,
 "logoRemuxDisplayMode": "composite",
 "logoStreamBadges": "auto",
 "mdblistKey": "",
 "networkTileColor": "",
 "posterAggregateProviderWeights": {
  "imdb": 3,
  "tomatoes": 2
 },
 "posterArtworkSource": "tmdb",
 "posterGenreBadgeMode": "both",
 "posterImageSize": "large",
 "posterImageText": "clean",
 "posterQualityBadgePreferences": [],
 "posterQualityBadgesMax": null,
 "posterQualityBadgesPosition": "auto",
 "posterRatingBadgeScale": 150,
 "posterRatingPreferences": [
  "imdb",
  "tomatoes",
  "tomatoesaudience",
  "myanimelist",
  "tmdb"
 ],
 "posterRatingStyle": "square",
 "posterRatingsLayout": "bottom",
 "posterRatingsMax": 4,
 "posterRemuxDisplayMode": "composite",
 "posterRingAudiencePriority": [],
 "posterRingCriticsPriority": [],
 "posterStreamBadges": "auto",
 "posterTrendingTagPosition": "auto",
 "posterTrendingTagStylePreset": "auto-minimal",
 "posterTrendingTagTextColor": "",
 "qualityBadgesSide": "left",
 "qualityBadgesTileAccentColor": "",
 "randomPosterFallback": "best",
 "randomPosterLanguage": "any",
 "randomPosterMinHeight": null,
 "randomPosterMinVoteAverage": null,
 "randomPosterMinVoteCount": null,
 "randomPosterMinWidth": null,
 "randomPosterText": "any",
 "releaseStatusBadgeStyle": null,
 "releaseStatusTileColor": "",
 "simklClientId": "",
 "thumbnailArtworkSource": "tmdb",
 "thumbnailBottomRatingsRow": false,
 "thumbnailEpisodeArtwork": "still",
 "thumbnailImageText": "clean",
 "thumbnailQualityBadgePreferences": [],
 "thumbnailQualityBadgesMax": null,
 "thumbnailRatingsMax": null,
 "thumbnailRemuxDisplayMode": "composite",
 "thumbnailStreamBadges": "auto",
 "tmdbIdScope": "soft",
 "tmdbKey": "",
 "version": 1,
 "xrdbKey": ""
}`
