/**
 * Community preset templates.
 * Each template supplies a partial SavedUiConfig that applies visual overrides.
 * Provider credentials (xrdbKey, tmdbKey, mdblistKey) are always preserved from the user's live config.
 */

export type CommunityTemplate = {
  id: string;
  name: string;
  description: string;
  author?: string;
  tags: string[];
  config: {
    version: 1;
    settings: Record<string, unknown>;
    proxy: Record<string, unknown>;
  };
};

export const COMMUNITY_TEMPLATES: CommunityTemplate[] = [
  {
    id: 'ratings-heavy',
    name: 'Ratings Heavy',
    description: 'High signal setup with many provider badges and dense quality metadata for power users.',
    tags: ['ratings', 'detailed', 'power'],
    config: {
      version: 1,
      settings: {
        posterRatingStyle: 'stacked',
        backdropRatingStyle: 'stacked',
        thumbnailRatingStyle: 'stacked',
        logoRatingStyle: 'plain',
        posterRatingsLayout: 'left-right',
        backdropRatingsLayout: 'right-vertical',
        thumbnailRatingsLayout: 'right-vertical',
        posterRatingsMax: 6,
        backdropRatingsMax: 6,
        thumbnailRatingsMax: 6,
        posterIconShape: 'squircle',
        backdropIconShape: 'squircle',
        thumbnailIconShape: 'squircle',
        logoIconShape: 'circle',
        qualityBadgesSide: 'right',
        posterQualityBadgesStyle: 'media',
        backdropQualityBadgesStyle: 'media',
        thumbnailQualityBadgesStyle: 'media',
        logoQualityBadgesStyle: 'plain',
        posterRatingPresentation: 'aggregate',
        backdropRatingPresentation: 'standard',
        thumbnailRatingPresentation: 'standard',
        logoRatingPresentation: 'standard',
        communityBadgeTheme: 'black',
      },
      proxy: {},
    },
  },
  {
    id: 'anime-tuned',
    name: 'Anime Tuned',
    description: 'Anime focused genre and rating layout with animation grouping and clear side aligned visibility.',
    tags: ['anime', 'genre', 'focused'],
    config: {
      version: 1,
      settings: {
        posterRatingStyle: 'stacked',
        backdropRatingStyle: 'stacked',
        thumbnailRatingStyle: 'stacked',
        logoRatingStyle: 'plain',
        posterRatingsLayout: 'left-right',
        backdropRatingsLayout: 'right-vertical',
        thumbnailRatingsLayout: 'right-vertical',
        posterRatingsMax: 5,
        backdropRatingsMax: 5,
        thumbnailRatingsMax: 5,
        posterGenreBadgeMode: 'both',
        backdropGenreBadgeMode: 'both',
        thumbnailGenreBadgeMode: 'both',
        logoGenreBadgeMode: 'both',
        posterGenreBadgeAnimeGrouping: 'animation',
        backdropGenreBadgeAnimeGrouping: 'animation',
        thumbnailGenreBadgeAnimeGrouping: 'animation',
        logoGenreBadgeAnimeGrouping: 'animation',
        aggregateAccentMode: 'dynamic',
        posterIconShape: 'squircle',
        backdropIconShape: 'squircle',
        thumbnailIconShape: 'squircle',
        logoIconShape: 'circle',
        posterQualityBadgesStyle: 'media',
        backdropQualityBadgesStyle: 'media',
        thumbnailQualityBadgesStyle: 'media',
        logoQualityBadgesStyle: 'plain',
        posterRatingPresentation: 'standard',
        backdropRatingPresentation: 'standard',
        thumbnailRatingPresentation: 'standard',
        logoRatingPresentation: 'standard',
      },
      proxy: {},
    },
  },
  {
    id: 'editorial-premium',
    name: 'Editorial Premium',
    description: 'Curated editorial look with premium poster treatment and disciplined support styling on other types.',
    tags: ['editorial', 'premium', 'curated'],
    config: {
      version: 1,
      settings: {
        posterRatingStyle: 'stacked',
        backdropRatingStyle: 'plain',
        thumbnailRatingStyle: 'plain',
        logoRatingStyle: 'plain',
        posterRatingsLayout: 'bottom',
        backdropRatingsLayout: 'center',
        thumbnailRatingsLayout: 'center',
        posterRatingsMax: 4,
        backdropRatingsMax: 3,
        thumbnailRatingsMax: 3,
        qualityBadgesSide: 'left',
        posterQualityBadgesStyle: 'community-badge',
        backdropQualityBadgesStyle: 'plain',
        thumbnailQualityBadgesStyle: 'plain',
        logoQualityBadgesStyle: 'plain',
        posterQualityBadgesMax: 3,
        posterIconShape: 'squircle',
        backdropIconShape: 'squircle',
        thumbnailIconShape: 'squircle',
        logoIconShape: 'circle',
        posterRatingPresentation: 'editorial',
        backdropRatingPresentation: 'standard',
        thumbnailRatingPresentation: 'standard',
        logoRatingPresentation: 'standard',
        communityBadgeTheme: 'black',
      },
      proxy: {},
    },
  },
  {
    id: 'compact-ring-focus',
    name: 'Compact Ring Focus',
    description: 'Poster first compact ring setup with clear aggregate emphasis and restrained companion type settings.',
    tags: ['ring', 'aggregate', 'poster'],
    config: {
      version: 1,
      settings: {
        posterRatingStyle: 'plain',
        backdropRatingStyle: 'plain',
        thumbnailRatingStyle: 'plain',
        logoRatingStyle: 'plain',
        posterRatingsLayout: 'right',
        backdropRatingsLayout: 'right-vertical',
        thumbnailRatingsLayout: 'right-vertical',
        posterRatingsMax: 4,
        backdropRatingsMax: 3,
        thumbnailRatingsMax: 3,
        posterIconShape: 'circle',
        backdropIconShape: 'circle',
        thumbnailIconShape: 'circle',
        logoIconShape: 'squircle',
        posterQualityBadgesStyle: 'plain',
        backdropQualityBadgesStyle: 'plain',
        thumbnailQualityBadgesStyle: 'plain',
        logoQualityBadgesStyle: 'plain',
        posterRatingPresentation: 'compact-ring',
        backdropRatingPresentation: 'standard',
        thumbnailRatingPresentation: 'standard',
        logoRatingPresentation: 'standard',
        posterRingValueSource: 'overall',
        posterRingProgressSource: 'overall',
        posterRingCenterOpacity: 78,
      },
      proxy: {},
    },
  },
  {
    id: 'logo-safe',
    name: 'Logo Safe',
    description: 'Logo first utility preset with restrained overlays to keep identity marks clean and readable.',
    tags: ['logo', 'safe', 'utility'],
    config: {
      version: 1,
      settings: {
        posterRatingStyle: 'plain',
        backdropRatingStyle: 'plain',
        thumbnailRatingStyle: 'plain',
        logoRatingStyle: 'plain',
        posterRatingsLayout: 'bottom',
        backdropRatingsLayout: 'center',
        thumbnailRatingsLayout: 'center',
        posterRatingsMax: 3,
        backdropRatingsMax: 2,
        thumbnailRatingsMax: 2,
        logoRatingsMax: 2,
        posterIconShape: 'circle',
        backdropIconShape: 'circle',
        thumbnailIconShape: 'circle',
        logoIconShape: 'circle',
        posterQualityBadgesStyle: 'plain',
        backdropQualityBadgesStyle: 'plain',
        thumbnailQualityBadgesStyle: 'plain',
        logoQualityBadgesStyle: 'plain',
        posterRatingPresentation: 'minimal',
        backdropRatingPresentation: 'minimal',
        thumbnailRatingPresentation: 'minimal',
        logoRatingPresentation: 'minimal',
      },
      proxy: {},
    },
  },
  {
    id: 'no-ratings-utility',
    name: 'No Ratings Utility',
    description: 'Artwork only mode that disables rating overlays across poster, backdrop, thumbnail, and logo.',
    tags: ['clean', 'artwork', 'none'],
    config: {
      version: 1,
      settings: {
        posterRatingStyle: 'plain',
        backdropRatingStyle: 'plain',
        thumbnailRatingStyle: 'plain',
        logoRatingStyle: 'plain',
        posterRatingPresentation: 'none',
        backdropRatingPresentation: 'none',
        thumbnailRatingPresentation: 'none',
        logoRatingPresentation: 'none',
        posterQualityBadgesStyle: 'plain',
        backdropQualityBadgesStyle: 'plain',
        thumbnailQualityBadgesStyle: 'plain',
        logoQualityBadgesStyle: 'plain',
      },
      proxy: {},
    },
  },
];
